# Generated by Django 4.2.7 on 2025-10-03 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('error_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('user_input', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('api_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=100)),
                ('model_used', models.CharField(max_length=50)),
                ('tokens_used', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('response_time', models.DecimalField(decimal_places=3, max_digits=8)),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_usage_log',
            },
        ),
    ]
