# Generated by Django 4.2.7 on 2025-10-03 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('weight_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_unit', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weight_log',
            },
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('water_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_log',
            },
        ),
        migrations.CreateModel(
            name='StepsLog',
            fields=[
                ('step_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('steps', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'steps_log',
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('macro_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('servings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('measurement', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('voice_input', models.TextField(blank=True, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('food', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('meal', models.ForeignKey(blank=True, db_column='meal_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.meal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_log',
            },
        ),
        migrations.CreateModel(
            name='CardioLog',
            fields=[
                ('cardio_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('cardio_type', models.CharField(max_length=100)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=8)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('distance_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cardio_log',
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurementLog',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('upper_arm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_arm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('leg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'body_measurement_log',
            },
        ),
    ]
