# Generated by Django 4.2.7 on 2025-10-03 22:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('sleep_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateField()),
                ('time_went_to_bed', models.TimeField()),
                ('time_got_out_of_bed', models.TimeField()),
                ('time_fell_asleep', models.TimeField(blank=True, null=True)),
                ('time_in_light_sleep', models.IntegerField(blank=True, null=True)),
                ('time_in_deep_sleep', models.IntegerField(blank=True, null=True)),
                ('time_in_rem_sleep', models.IntegerField(blank=True, null=True)),
                ('number_of_times_woke_up', models.IntegerField(blank=True, null=True)),
                ('resting_heart_rate', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sleep_log',
            },
        ),
        migrations.CreateModel(
            name='HealthMetricsLog',
            fields=[
                ('health_metrics_id', models.AutoField(primary_key=True, serialize=False)),
                ('resting_heart_rate', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('morning_energy', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('soreness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('illness_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date_time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_metrics_log',
            },
        ),
    ]
