# Generated by Django 4.2.7 on 2025-10-03 22:17

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    """Populate initial data for AccessLevel, Unit, and ActivityLevel tables"""
    AccessLevel = apps.get_model('users', 'AccessLevel')
    Unit = apps.get_model('users', 'Unit')
    ActivityLevel = apps.get_model('users', 'ActivityLevel')
    
    # Create access levels
    AccessLevel.objects.get_or_create(role_name='admin')
    AccessLevel.objects.get_or_create(role_name='user')
    AccessLevel.objects.get_or_create(role_name='guest')
    
    # Create units
    Unit.objects.get_or_create(unit_name='imperial')
    Unit.objects.get_or_create(unit_name='metric')
    
    # Create activity levels
    ActivityLevel.objects.get_or_create(
        name='Sedentary',
        defaults={'description': 'Little or no exercise'}
    )
    ActivityLevel.objects.get_or_create(
        name='Lightly Active',
        defaults={'description': 'Light exercise/sports 1-3 days/week'}
    )
    ActivityLevel.objects.get_or_create(
        name='Moderately Active',
        defaults={'description': 'Moderate exercise/sports 3-5 days/week'}
    )
    ActivityLevel.objects.get_or_create(
        name='Very Active',
        defaults={'description': 'Hard exercise/sports 6-7 days a week'}
    )
    ActivityLevel.objects.get_or_create(
        name='Extremely Active',
        defaults={'description': 'Very hard exercise, physical job or 2x training'}
    )


def reverse_populate_initial_data(apps, schema_editor):
    """Reverse the data population"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_populate_initial_data),
    ]
