# Generated by Django 4.2.7 on 2025-10-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251003_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.ForeignKey(blank=True, db_column='access_level_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.accesslevel'),
        ),
    ]
