# Generated by Django 4.2.7 on 2026-03-09 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteKey',
            fields=[
                ('invite_key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invite_key',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='invite_key',
            field=models.OneToOneField(blank=True, db_column='invite_key_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='users.invitekey'),
        ),
    ]
