# Generated by Django 4.2.7 on 2025-10-03 22:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('muscles_id', models.AutoField(primary_key=True, serialize=False)),
                ('muscle_name', models.CharField(max_length=100, unique=True)),
                ('muscle_group', models.CharField(choices=[('legs', 'Legs'), ('core', 'Core'), ('arms', 'Arms'), ('back', 'Back'), ('chest', 'Chest'), ('other', 'Other')], max_length=20)),
            ],
            options={
                'db_table': 'muscles',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workouts_id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=200)),
                ('equipment_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('plate_machine', 'Plate Machine'), ('cable_machine', 'Cable Machine'), ('bodyweight', 'Bodyweight')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('workout_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('rir', models.IntegerField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(db_column='workout_id', on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
            options={
                'db_table': 'workout_log',
            },
        ),
        migrations.CreateModel(
            name='MuscleLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('importance', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('day_worked', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('muscle_name', models.ForeignKey(db_column='muscle_name', on_delete=django.db.models.deletion.CASCADE, to='workouts.muscle', to_field='muscle_name')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'muscle_log',
            },
        ),
        migrations.CreateModel(
            name='WorkoutMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('muscle', models.ForeignKey(db_column='muscle_id', on_delete=django.db.models.deletion.CASCADE, to='workouts.muscle')),
                ('workout', models.ForeignKey(db_column='workout_id', on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
            options={
                'db_table': 'workout_muscle',
                'unique_together': {('workout', 'muscle')},
            },
        ),
    ]
