# Generated by Django 4.2.7 on 2025-10-11 17:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('splits_id', models.AutoField(primary_key=True, serialize=False)),
                ('split_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'splits',
            },
        ),
        migrations.CreateModel(
            name='SplitDay',
            fields=[
                ('split_days_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=100)),
                ('day_order', models.IntegerField()),
                ('split', models.ForeignKey(db_column='splits_id', on_delete=django.db.models.deletion.CASCADE, to='workouts.split')),
            ],
            options={
                'db_table': 'split_days',
            },
        ),
        migrations.RenameField(
            model_name='musclelog',
            old_name='id',
            new_name='muscle_log_id',
        ),
        migrations.RemoveField(
            model_name='musclelog',
            name='day_worked',
        ),
        migrations.AddField(
            model_name='musclelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='make_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='rest_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='SplitDayTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_activation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('muscle', models.ForeignKey(db_column='muscle_id', on_delete=django.db.models.deletion.CASCADE, to='workouts.muscle')),
                ('split_day', models.ForeignKey(db_column='split_day_id', on_delete=django.db.models.deletion.CASCADE, to='workouts.splitday')),
            ],
            options={
                'db_table': 'split_day_targets',
                'unique_together': {('split_day', 'muscle')},
            },
        ),
    ]
