# Generated by Django 4.2.7 on 2025-10-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_split_splitday_rename_id_musclelog_muscle_log_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musclelog',
            old_name='importance',
            new_name='priority',
        ),
    ]
