# Generated by Django 4.2.7 on 2025-10-25 04:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0003_rename_importance_musclelog_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='attribute_inputs',
            field=models.JSONField(blank=True, default=dict, help_text='Input values for attributes'),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='muscle_group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='musclelog',
            name='priority',
            field=models.IntegerField(default=80, help_text='Muscle priority 1-100, default 80', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='split',
            name='split_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='split',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='splitdaytarget',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='splitdaytarget',
            name='target_activation',
            field=models.IntegerField(help_text='Target activation for this muscle on this day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='attributes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='rest_time',
            field=models.IntegerField(blank=True, help_text='Rest time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='rir',
            field=models.IntegerField(blank=True, help_text='Reps in reserve 0-10', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='workoutmuscle',
            name='activation_rating',
            field=models.IntegerField(help_text='Muscle activation rating 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='workoutmuscle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='musclelog',
            unique_together={('user', 'muscle_name')},
        ),
        migrations.AlterUniqueTogether(
            name='splitday',
            unique_together={('split', 'day_order')},
        ),
    ]
