# Generated by Django 4.2.7 on 2025-10-03 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=200, unique=True)),
                ('serving_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trans_fat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('iron', models.DecimalField(decimal_places=2, max_digits=8)),
                ('magnesium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vitamin_a', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vitamin_c', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vitamin_d', models.DecimalField(decimal_places=2, max_digits=8)),
                ('caffeine', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_group', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('grain', 'Grain'), ('protein', 'Protein'), ('dairy', 'Dairy'), ('other', 'Other')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meals',
                'unique_together': {('user', 'meal_name')},
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('meal', models.ForeignKey(db_column='meal_id', on_delete=django.db.models.deletion.CASCADE, to='foods.meal')),
            ],
            options={
                'db_table': 'meals_foods',
                'unique_together': {('meal', 'food')},
            },
        ),
    ]
