# Generated by Django 4.2.7 on 2025-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='make_public',
            field=models.BooleanField(default=False),
        ),
    ]
